# syntax=docker.io/docker/dockerfile:1

# This dockerfile is used to build the development environment for the application.
# The image should NEVER be used in any production environment.

FROM node:22-alpine@sha256:d2166de198f26e17e5a442f537754dd616ab069c47cc57b889310a717e0abbf9 AS build-base
RUN corepack enable pnpm

# Alpine uses musl instead of glibc and TypeORM has methods that require it.
RUN apk add --no-cache libc6-compat

# 1. Install build dependencies
FROM build-base AS init-provider
RUN apk add --no-cache dumb-init

# 2. Install all dependencies (including dev)
FROM build-base AS deps
WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile --prefer-offline

# 3. Copy application files and run.
FROM build-base AS runner
WORKDIR /app

RUN mkdir -p /app/dist && chown -R node:node /app

COPY --chown=node:node . .
COPY --from=init-provider --chown=node:node /usr/bin/dumb-init /usr/bin/dumb-init
COPY --from=deps --chown=node:node /app/node_modules ./node_modules

USER node

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["pnpm", "start:dev"]