#!/bin/bash
# scripts/export-seed-data.sh
# Exports clean seed data for RDA Gateway database
# Includes: vocabulary, reference tables, working groups
# Excludes: user data (resource, individual, institution, website_* tables)

set -e

# Configuration
DB_NAME="${DATABASE_NAME:-rda_gateway}"
DB_USER="${DATABASE_USERNAME:-postgres}"
CONTAINER_NAME="rda-postgres-database"
OUTPUT_FILE="${1:-seed_data.sql}"

# Tables to include (reference/vocabulary data only - NO user data)
# This explicitly excludes: resource, individual, institution, website_*, deduplicated_*
INCLUDE_TABLES=(
    "vocabulary"
    "gorc_element"
    "gorc_atribute"
    "discipline"
    "keyword"
    "pathway"
    "relation"
    "uri_type"
    "org_type"
    "institution_role"
    "annotator_metadata"
    "working_group"
    "interest_group"
    "group_group"
)

echo "Exporting seed data to ${OUTPUT_FILE}..."
echo "Tables to export: ${INCLUDE_TABLES[*]}"

# Create output file with header
cat > "$OUTPUT_FILE" << 'EOF'
-- RDA Gateway Seed Data
-- This file contains reference/vocabulary data only (no user data)
-- Generated by scripts/export-seed-data.sh

-- First, apply schema migrations
EOF

# Append migrations.sql content
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MIGRATIONS_FILE="$SCRIPT_DIR/../migrations.sql"

if [ -f "$MIGRATIONS_FILE" ]; then
    echo "Including migrations.sql..."
    echo "" >> "$OUTPUT_FILE"
    echo "-- === MIGRATIONS ===" >> "$OUTPUT_FILE"
    cat "$MIGRATIONS_FILE" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
else
    echo "Warning: migrations.sql not found at $MIGRATIONS_FILE"
fi

# Build pg_dump table arguments
TABLE_ARGS=""
for table in "${INCLUDE_TABLES[@]}"; do
    TABLE_ARGS="$TABLE_ARGS -t $table"
done

# Export data for selected tables using Docker container
echo "" >> "$OUTPUT_FILE"
echo "-- === SEED DATA ===" >> "$OUTPUT_FILE"

docker exec "$CONTAINER_NAME" pg_dump \
    -U "$DB_USER" \
    -d "$DB_NAME" \
    --no-owner \
    --no-privileges \
    --data-only \
    --inserts \
    $TABLE_ARGS \
    >> "$OUTPUT_FILE" 2>/dev/null || {
        echo "Warning: Some tables may not exist yet. Continuing..."
    }

# Count inserts
INSERT_COUNT=$(grep -c "^INSERT INTO" "$OUTPUT_FILE" 2>/dev/null || echo "0")

echo ""
echo "Export complete: ${OUTPUT_FILE}"
echo "Tables exported: ${#INCLUDE_TABLES[@]}"
echo "INSERT statements: ${INSERT_COUNT}"
echo ""
echo "To import this seed data into a fresh database:"
echo "  docker exec -i $CONTAINER_NAME psql -U $DB_USER -d $DB_NAME < ${OUTPUT_FILE}"
